Added Time
techlahoma/thunderplains-2023 pull request #45
Opened 2023-10-26 20:22 UTC by hkbertoson

Added time underneath the event details to resolve #34

2023-10-26 20:56 UTC, kacollins requested changes
I believe the conference starts at 9:00, not 9:30.

2023-10-26 21:11 UTC, hkbertoson commented
> I believe the conference starts at 9:00, not 9:30.

Fixed it.

2023-10-26 21:11 UTC, kacollins approved these changes

2023-10-27 19:23 UTC, vlucas approved these changes

2023-10-27 19:23 UTC, merged